# src/latest_ai_development/config/tasks.yaml
research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A small 10 phrase reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: report.md

linkedin_post_task:
  description: >
    Create a medium-length LinkedIn post about {topic} for developers and students (basic to intermediate level)
    with a casual, conversational tone. Structure the post as: 1) Hook, 2) Explanation paragraph(s),
    3) One engaging question, 4) Clear CTA. Include at most one emoji. Append 2-3 relevant, trending hashtags.
    Also provide a separate realistic, fun image prompt aligned with the content.
  expected_output: >
    Markdown without code fences. Sections:
    - Post: The full LinkedIn post text (includes hook, explanation, one question, CTA, <=1 emoji).
    - Hashtags: 2-3 hashtags.
    - Image Prompt: A short, realistic and fun description for image generation, tied to the post.
  agent: linkedin_post_creator
  output_file: output/linkedin_post.md